meta_product_name: "Sitcom"
meta_title: "Sitcom - Shows Community"
meta_description: "Discover what shows your friends liked"
meta_image: "logositcomlong1200x630.png" # should exist in `app/assets/images/`
twitter_account: "@AranLive_"   # required for Twitter Cards
